#!/bin/bash
# CSS Bundle Generator for cli-session-hub-viewer
# Usage:
#   bash scripts/build-css.sh          # Build once
#   bash scripts/build-css.sh --watch  # Watch + auto-rebuild

shopt -s nullglob

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CSS_DIR="$PROJECT_ROOT/assets/css"
OUTPUT="$PROJECT_ROOT/assets/bundle.css"

# Build function
build_css() {
    echo "🎨 Building CSS bundle..."

    cat > "$OUTPUT" << 'EOF'
/* BUNDLE CSS - Auto-generated by scripts/build-css.sh */
/* Do not edit directly - modify source files in assets/css/ */

EOF

    append_file() {
        local file="$1"
        if [[ -f "$file" ]]; then
            echo "/* === $(basename "$file") === */" >> "$OUTPUT"
            cat "$file" >> "$OUTPUT"
            echo "" >> "$OUTPUT"
            echo "  ✓ $(basename "$file")"
        fi
    }

    append_dir() {
        local dir="$1"
        local name="$2"
        if [[ -d "$dir" ]]; then
            echo "📁 $name"
            for file in "$dir"/*.css; do
                [[ -f "$file" ]] && append_file "$file"
            done
        fi
    }

    # ITCSS Order
    echo "📁 settings"
    append_file "$CSS_DIR/settings/_theme-dark.css"
    append_file "$CSS_DIR/settings/_theme-light.css"
    append_file "$CSS_DIR/settings/_theme-golden.css"
    append_file "$CSS_DIR/settings/_theme-pistachio.css"
    append_file "$CSS_DIR/settings/_theme-dark-golden.css"
    append_file "$CSS_DIR/settings/_theme-dark-pistachio.css"
    append_dir "$CSS_DIR/tools" "tools"
    append_dir "$CSS_DIR/generic" "generic"
    append_dir "$CSS_DIR/elements" "elements"
    append_dir "$CSS_DIR/objects" "objects"
    append_dir "$CSS_DIR/components" "components"
    append_dir "$CSS_DIR/utilities" "utilities"
    append_dir "$CSS_DIR/animations" "animations"
    append_dir "$CSS_DIR/accessibility" "accessibility"
    append_dir "$CSS_DIR/responsive" "responsive"

    echo ""
    echo "✅ Bundle: $(wc -c < "$OUTPUT" | tr -d ' ') bytes"
}

# Watch function
watch_css() {
    echo "🔍 Watching CSS changes in $CSS_DIR..."
    echo "💡 Keep this terminal open while running 'dx serve'"
    echo ""

    build_css

    get_checksums() {
        find "$CSS_DIR" -type f -name "*.css" -exec md5 {} \; 2>/dev/null | sort
    }

    PREV_CHECKSUMS=$(get_checksums)

    while true; do
        sleep 2
        CURR_CHECKSUMS=$(get_checksums)

        if [ "$PREV_CHECKSUMS" != "$CURR_CHECKSUMS" ]; then
            echo ""
            echo "🔄 CSS changed..."
            build_css
            PREV_CHECKSUMS="$CURR_CHECKSUMS"
        fi
    done
}

# Main
if [[ "$1" == "--watch" || "$1" == "-w" ]]; then
    watch_css
else
    build_css
fi
